# Generated by Django 5.2.5 on 2025-08-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('opnsense', 'OPNsense')], default='manual', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.FileField(upload_to='crls/original/')),
                ('der_file', models.FileField(blank=True, null=True, upload_to='crls/der/')),
                ('pem_file', models.FileField(blank=True, null=True, upload_to='crls/pem/')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('next_update', models.DateTimeField(blank=True, null=True)),
                ('revoked_count', models.IntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=128)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crls', to='crls.ca')),
            ],
        ),
        migrations.CreateModel(
            name='OpnsenseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=64)),
                ('remote_path', models.CharField(max_length=512)),
                ('ssh_key_path', models.CharField(max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opnsense_source', to='crls.ca')),
            ],
        ),
    ]
