# Generated by Django 5.2.5 on 2025-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opnsensesource',
            name='auth_method',
            field=models.CharField(choices=[('key', 'SSH key'), ('password', 'Password')], default='key', max_length=16),
        ),
        migrations.AddField(
            model_name='opnsensesource',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='remote_path',
            field=models.CharField(default='/usr/local/share/certs/ca-rootopensense-0.crl', max_length=512),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='ssh_key_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
