# Generated by Django 5.2.5 on 2025-08-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0002_opnsensesource_auth_method_opnsensesource_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crl',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('opnsense', 'OPNsense'), ('http', 'HTTP URL')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='HttpSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('verify_tls', models.BooleanField(default=True)),
                ('auth_method', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('header', 'Custom Header')], default='none', max_length=16)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('header_name', models.CharField(blank=True, max_length=128)),
                ('header_value', models.CharField(blank=True, max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('timeout_seconds', models.IntegerField(default=20)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='http_source', to='crls.ca')),
            ],
        ),
    ]
