# Generated by Django 5.2.5 on 2025-08-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0003_alter_crl_source_httpsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='issuer_cert_pem',
            field=models.FileField(blank=True, null=True, upload_to='ca/certs/'),
        ),
        migrations.CreateModel(
            name='IssuedCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_decimal', models.CharField(db_index=True, max_length=64)),
                ('cert_pem', models.FileField(upload_to='issued/certs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certs', to='crls.ca')),
            ],
        ),
        migrations.CreateModel(
            name='OcspSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_cert_pem', models.FileField(upload_to='ocsp/certs/')),
                ('signer_key_pem', models.FileField(upload_to='ocsp/keys/')),
                ('signer_key_password', models.CharField(blank=True, max_length=256)),
                ('include_signer_in_response', models.BooleanField(default=True)),
                ('strict_unknown', models.BooleanField(default=False, help_text="If enabled, serials not in CRL and not in IssuedCerts return 'unknown' instead of 'good'.")),
                ('next_update_seconds', models.IntegerField(default=3600, help_text='Fallback TTL if CRL has no Next Update.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocsp_signer', to='crls.ca')),
            ],
        ),
    ]
