# Generated by Django 5.2.5 on 2025-08-30 21:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0004_ca_issuer_cert_pem_issuedcert_ocspsigner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocspsigner',
            name='last_response_at',
        ),
        migrations.AddField(
            model_name='ca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='httpsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuedcert',
            name='serial_hex',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='issuedcert',
            name='subject_cn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ocspsigner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opnsensesource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='issuer_cert_pem',
            field=models.FileField(blank=True, null=True, upload_to='pki/'),
        ),
        migrations.AlterField(
            model_name='crl',
            name='der_file',
            field=models.FileField(blank=True, null=True, upload_to='crl/der/'),
        ),
        migrations.AlterField(
            model_name='crl',
            name='original_file',
            field=models.FileField(upload_to='crl/original/'),
        ),
        migrations.AlterField(
            model_name='crl',
            name='pem_file',
            field=models.FileField(blank=True, null=True, upload_to='crl/pem/'),
        ),
        migrations.AlterField(
            model_name='crl',
            name='revoked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crl',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='crl',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual upload'), ('opnsense', 'OPNsense'), ('http', 'HTTP/HTTPS')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='auth_method',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'HTTP Basic'), ('header', 'Custom header')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='header_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='header_value',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='password',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='httpsource',
            name='username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='issuedcert',
            name='ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued', to='crls.ca'),
        ),
        migrations.AlterField(
            model_name='issuedcert',
            name='cert_pem',
            field=models.FileField(upload_to='issued/'),
        ),
        migrations.AlterField(
            model_name='issuedcert',
            name='serial_decimal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='ocspsigner',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ocspsigner',
            name='next_update_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name='ocspsigner',
            name='signer_cert_pem',
            field=models.FileField(upload_to='ocsp/'),
        ),
        migrations.AlterField(
            model_name='ocspsigner',
            name='signer_key_password',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='ocspsigner',
            name='signer_key_pem',
            field=models.FileField(upload_to='ocsp/'),
        ),
        migrations.AlterField(
            model_name='ocspsigner',
            name='strict_unknown',
            field=models.BooleanField(default=False, help_text='If enabled, return UNKNOWN when a serial is not present in IssuedCerts.'),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='password',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='remote_path',
            field=models.CharField(help_text='Remote file path to the CRL', max_length=512),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='ssh_key_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='opnsensesource',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
