# Generated by Django 5.2.5 on 2025-09-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0005_remove_ocspsigner_last_response_at_ca_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='cert_pem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ca',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ca',
            name='key_pem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ca',
            name='method',
            field=models.CharField(choices=[('import', 'Import existing CA'), ('internal', 'Create internal CA')], default='import', max_length=16),
        ),
        migrations.AddField(
            model_name='ca',
            name='next_serial',
            field=models.BigIntegerField(default=1),
        ),
    ]
