# Generated by Django 5.2.5 on 2025-09-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0006_ca_cert_pem_ca_description_ca_key_pem_ca_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ca',
            name='method',
        ),
        migrations.CreateModel(
            name='RevokedCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_decimal', models.CharField(max_length=256)),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_revoked', to='crls.ca')),
            ],
            options={
                'unique_together': {('ca', 'serial_decimal')},
            },
        ),
    ]
