# Generated by Django 5.2.5 on 2025-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0007_remove_ca_description_remove_ca_method_revokedcert'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcert',
            name='revoke_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='issuedcert',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuedcert',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
