# Generated by Django 5.2.5 on 2025-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crls', '0008_issuedcert_revoke_reason_issuedcert_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcert',
            name='key_pem',
            field=models.FileField(blank=True, null=True, upload_to='issued/'),
        ),
        migrations.AddField(
            model_name='issuedcert',
            name='p12_file',
            field=models.FileField(blank=True, null=True, upload_to='issued/'),
        ),
    ]
